<h2>Brush Rush</h2>

<div class="gallery">

	<div class="thumbs">
		<img src="/images/game_art/br/thumbs/PB1.png" />
		<img src="/images/game_art/br/thumbs/PB2.png" />
		<img src="/images/game_art/br/thumbs/PB3.png" />
		<img src="/images/game_art/br/thumbs/PB4.png" />
		<img src="/images/game_art/br/thumbs/PB5.png" />
		<img src="/images/game_art/br/thumbs/PB6.png" />
		<img src="/images/game_art/br/thumbs/PB7.png" />
		<img src="/images/game_art/br/thumbs/PB8.png" />
	</div>


	<div class="viewer"></div>

</div> 

<center><h4>Players must use their quick reactions and wits to trick their opponents, all the while painting the town red! </h4></center>

<h3>Concept and Design</h3>

<div class="info_2col">
	<p>
		<span class="field">Engine</span>
		<span class="value">Unity</span>
	</p>
	<p>
		<span class="field">Programming</span>
		<span class="value">Unity Javascript</span>
	</p>
	<p>
		<span class="field">Art</span>
		<span class="value">Photoshop, 3DS Max</span>
	</p>
</div>

<div class="info_2col">
	<p>
		<span class="field">Artist & Designer</span>
		<span class="value">Anna Lapinsh</span>
	</p>
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">James Older</span>
	</p>
</div>

<div class="text_body">

<h4>About</h4>
	<p>The brief was to create a game with known and unkown information. A multi player game seemed like just the right fit. 
	We wanted a really competitive game, one where you're never sure if you're winning or not.
	Brush Rush had a lot of problems actually coming to fruition - at the time we were also working on our dissertations! 
	However I'm still madly in love with it and I work on it from time to time. Hopefully it will be completed one day. </p>

<h4>Concept</h4>
	<p>Players are challenged to paint as much of the Arena's surface before the time runs out. 
	Players will compete against an Opponent that is trying to paint as much of their Arena's surface at the same time. 
The winner of the game is the Player who colours the largest amount of the Arena when the time runs out. 
</p>
	
<h4>Gameplay</h4>
<img src="/images/game_art/br/blockpaint.png" align="right" hspace="20" vspace="10" />
<p><b>Controls</b><br>
	The game is played on a grid so Players will move one square at a time on the grid. 
	Players will control this movement with the WASD keys. 
	When Players want to paint a square on the arena, they will use the left mouse button. </p>

<p><b>The Arena</b><br>
	The Arena will be a gridded play space that can be of numerous shapes and sizes. The exact shape and size will be determined on a later date. </p>
	
<p><b>Painting</b><br>
	Players can paint any square within the Arena; however doing so will completely drain their Paint Drop. The Player's Paint Drop will then take five seconds (exact time TBD) to refill. While the Paint Drop is refilling, Players will be able to move around the Arena but they will not be able to paint until their Drop is completely full.</p>
	
<p><b>Painting Advanced</b><br>
	If Players paint a square that has already been painted by their Opponent, the Player is stunned and their Paint Drop is emptied. 
	<br><br>This gives the Opponent a large opportunity to paint while the Player cannot and where much of the game's strategy will come from. It will be in the Player's interest to trick their Opponent into Painting the squares that they have already painted. Players will be able to achieve this by using their knowledge that the other player is aware of the last four moves that they took.</p>

<p><b>Opponent</b><br>
	There are two things Players will have to bear in mind about their Opponent: 
<ol><li>Players will be unable to see where their Opponent is, although Players will be able to see the last four squares that their Opponent has stepped on.</li>
<li>Players will be unable to see where their Opponent has painted.</li></ol></p>
	
<p><b>Power-ups</b><br>
	Paint by Speed will feature Power-ups that will be given to players to create a more dynamic experience. These Power-ups will be given to players when they pick up a Power-up Box. Once picked up, Players will be randomly assigned one of the following Power-ups:
<ul><li>Fake Power-up - this will create a Power-up Box that only the Opponent can see, however when the Opponent picks up this box their paint is instantly drained. </li>
<li>Paint Drop - the Player instantly gets all of their Paint restored.</li>
<li>Duplicate - this creates a secondary path that is the opposite direction to the Player's movement, confusing their Opponent. </li>
<li>Invisibility - the Opponent will no longer be able to see the other Player's path. </li></ul>
</p>


	
</div>