<h2>Games</h2>


<a href="/games/kitchen-panic"><img src="/images/index_art/games/1.png" align="left" hspace="10" vspace="10" border="0"/></a> <h3><a href="/games/kitchen-panic">Kitchen Panic</a></h3>
<p>
The goal of the game is to complete a recipe by catching enough required ingredients. 
The ingredients fall from the top of the screen. The player controls a large disk with 
several holes, into which he must catch the ingredients. The ingredients that pass through 
the holes are considered caught by the player.
<br><br><br><br><a href="/games/kitchen-panic">Read more...</a>

</p>
<br><br>

<a href="/games/brush-rush"><img src="/images/index_art/games/2.png" align="left" hspace="10" vspace="10" border="0"/></a> <h3><a href="/games/brush-rush">Brush Rush</a></h3>
<p>
Players are challenged to paint as much of the Arena's surface before the time runs out. 
Players will compete against an Opponent that is trying to paint as much of their Arena's surface at the same time. 
The winner of the game is the Player who colours the largest amount of the Arena when the time runs out.
<br><br><br><br><a href="/games/brush-rush">Read more...</a>

</p>
<br><br>

<a href="/games/space-constructor"><img src="/images/index_art/games/3.png" align="left" hspace="10" vspace="10" border="0"/></a> <h3><a href="/games/space-constructor">Space Constructor</a></h3>
<p>
Players are tasked with climbing as high as they can in this puzzle action game. 
As the player starts his ascent, his energy starts to constantly degrade. 
To keep himself energised the player must collect Stars that litter the sky. 
However, collecting these starts may make the tower less sturdy and cause some of the tower to collapse. 
Players will have to use quick thinking to build a tower that truly stretches out to the heavens.
<br><br><br><a href="/games/space-constructor">Read more...</a>

</p>
<br><br>

<a href="/games/moustache"><img src="/images/index_art/games/4.png" align="left" hspace="10" vspace="10" border="0"/></a> <h3><a href="/games/moustache">Moustache</a></h3>
<p>
Players take control of a 1930's gentleman who has been pulled into a surrealist world. 
Upon entering this world, a mysterious villain steals your beautiful and manly moustache. 
The player must then traverse dangerous and weird obstacles, solve puzzles and discover the true meaning of this strange world, 
ultimately finding and defeating the villain to get his moustache back and find his way home.
<br><br><br><a href="/games/moustache">Read more...</a>

</p>
<br><br>

<a href="/games/pandamine"><img src="/images/index_art/games/5.png" align="left" hspace="10" vspace="10" border="0"/></a> <h3><a href="/games/pandamine">Pandamine</a></h3>
<p>
Players must escape the dark cave with the use of their magic wand. 
Not only does it light their way, it can interact with the environment to activate platforms and help solve puzzles. 
Coins help the Player by leading the way, as well as giving him bonus points.
<br><br><br><br><a href="/games/pandamine">Read more...</a>

</p>
<br><br>

<a href="/games/steam-express"><img src="/images/index_art/games/6.png" align="left" hspace="10" vspace="10" border="0"/></a> <h3><a href="/games/steam-express">Steam Express</a></h3>
<p>
Players are responsible for picking up packages and delivering them to the station. 
They can control the tracks by switching which way the junctions are pointing. 
The game gets harder as other trains enter the tracks and the Player must keep his eye on everything to avoid collisions.
<br><br><br><br><a href="/games/steam-express">Read more...</a>

</p>
<br><br>

<a href="/games/medusa"><img src="/images/index_art/games/7.png" align="left" hspace="10" vspace="10" border="0"/></a> <h3><a href="/games/medusa">Medusa</a></h3>
<p>
The game is played from a bird's eye view. 
The point of the game is to stay alive and kill your enemies. 
Different enemies will use different tactics, so planning an attack and quick thinking is vital. 
There is a set number of levels for the Player to battle through, at which point he will win the game.
<br><br><br><br><a href="/games/medusa">Read more...</a>

</p>
<br><br>