<h2>Medusa</h2>


<center><embed src="http://www.lapinsh.com/gamefiles/FINAL.swf" 
volume="0"
width="550" 
height="400" 

pluginspage="http://www.macromedia.com/go/getflashplayer"
></embed></center><br>

<center><h4>Get revenge on your foes by turning them to stone</h4></center>

<h3>Concept and Design</h3>

<div class="info_2col">
	<p>
		<span class="field">Engine</span>
		<span class="value">Flash</span>
	</p>
	<p>
		<span class="field">Programming</span>
		<span class="value">AS2</span>
	</p>
	<p>
		<span class="field">Art</span>
		<span class="value">Flash, Photoshop</span>
	</p>
</div>

<div class="info_2col">
	<p>
		<span class="field">Programmer & Artist & Designer</span>
		<span class="value">Anna Lapinsh</span>
	</p>
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">James Older</span>
	</p>
	
	<p>
		<span class="field">Programmer & Artist & Designer</span>
		<span class="value">Aaron Roberts</span>
	</p>	
</div>


<div class="text_body">

<h4>About</h4>
	<p>The first game that I ever made! This is the first project that I worked on at my degree. The brief was to design a game based on a myth or legend.
	This was my first experience of AS2 coding. Since my team was small and we were all quite new to it, we all pitched in to code. 
	I had made sprite sheets before, so I knew the theory behind game art. It was really exciting to see my art actually used in something interactive.</p>

<h4>Concept</h4>
	<p>The game is played from a bird's eye view. The point of the game is to stay alive and kill your enemies. 
	Different enemies will use different tactics, so planning an attack and quick thinking is vital. There is a set number of levels for the 
	Player to battle through, at which point he will win the game. 
	</p>
	
<h4>Gameplay</h4>
<p><b>Movement</b><br>
	The Player controls Medusa - a stationary figure. 
	He uses the mouse to control which way she is looking. Medusa can turn 360 degrees. </p>
	
<p><b>Stoney Gaze</b><br>
	When the Player clicks the right mouse button, he activates Medusa's Stoney Gaze. Medusa cannot be turned while the Stoney Gaze is activated. 
	The Gaze pulses out from Medusa into a sort of cone of vision. If the Gaze hits any enemies, they turn to stone. 
	The Gaze cannot penetrate through any stone objects or stone enemies.</p>
	
<p><b>Enemies</b><br>
Enemies walk towards Medusa at a steady pace from different corners of the screen. If the Enemies hit an object or another enemy, they will walk around it.
	There are three types of enemies:
	<ul>
	<li>Swordsmen are basic enemies that charge at Medusa and try to kill her.</li>	
	<li>Axemen can bash through stone enemies and remove them from the game without having to walk around them.</li>
	<li>Archers can shoot from behind stone enemies. If an arrow hits Medusa, she becomes stunned and cannot shoot or turn for some time.</li>
	</ul></p>
	
<p><b>Winning</b><br>
	The object of the game is to complete all the levels and not get killed by the enemies. If Medusa gets hit by an enemy, she will die and the game will end.</p>
	
</div>