<h2>Moustache</h2>


<div class="gallery">

	<div class="thumbs">
		<img src="/images/game_art/surr/thumbs/sur4.png" />
		<img src="/images/game_art/surr/thumbs/sur1.png" />
		<img src="/images/game_art/surr/thumbs/sur2.png" />
		<img src="/images/game_art/surr/thumbs/sur3.png" />
		<img src="/images/game_art/surr/thumbs/sur5.png" />
		<img src="/images/game_art/surr/thumbs/sur6.png" />
			<img src="/images/game_art/surr/thumbs/sur7.png" />
		<div class="fake_img" style="background: url(/images/game_art/surr/thumbs/sur8.png) top left no-repeat;" onclick="Site.toggleView(this, 'anim4');"></div>
	</div>


	<div class="viewer"></div>
	
	<p><b>Elephant</b>
	<br>2010
	<br>The Elephant is a massive character that Players can climb into.
	</p>

	<p><b>First Stage Concept Rough</b>
	<br>2010
	<br>The rough of what the first stage will look like. 
	</p>

	<p><b>First Stage: The Cave</b>
	<br>2010
	<br>Players are challenged with making it from their bedroom to the exit of the cave.
	</p>
	
	<p><b>Third Stage: The Type Writer in the Sky</b>
	<br>2010
	<br>The lettering here had to be carefully made so Players could easily understand it. The Bleeding Eye closes after the riddle is solved.
	</p>
	
	<p><b>Outfit Concepts</b>
	<br>2010
	<br>A few outfit and moustache samples.
	</p>
	
	<p><b>Character Concepts</b>
	<br>2010
	<br>Some concepts of the main character. 
	</p>	
	
	<p><b>Character Sprite Sheet</b>
	<br>2010
	<br>The sprite sheet for the main character's walk and climb cycle. 
	</p>	
	
	<p><b>Character Walk Cycle</b>
	<br>2010
	<br>The final walk cycle.
	</p>	
	
<div id="anim4" class="viewer_set" style="padding-top: 80px;">
		<img src="/images/game_art/surr/sur_walk.gif" /></div>
</div> 






<br><br><center><h4>Partake in one of 1930's most tragic stories: the theft of a man's moustache.  </h4></center>


<h3>Concept and Design</h3>

<div class="info_2col">
	<p>
		<span class="field">Engine</span>
		<span class="value">XNA</span>
	</p>
	<p>
		<span class="field">Programming</span>
		<span class="value">C#</span>
	</p>
	<p>
		<span class="field">Art</span>
		<span class="value">Photoshop</span>
	</p>
</div>

<div class="info_2col">
	<p>
		<span class="field">Artist & Designer</span>
		<span class="value">Anna Lapinsh</span>
	</p>
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">James Older</span>
	</p>
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">Chris Lee</span>
	</p>
	<p>
		<span class="field">Artist & Designer</span>
		<span class="value">Calvin Simpson</span>
	</p>	
</div>

<div class="text_body">
	
<h4>About</h4> <img src="/images/game_art/surr/sur_bagface_sprite.gif" align="right" hspace="10" vspace="10" />
	<p>This is the first game of our second year of the degree course. 
	We were learning C# and getting to grips with XNA while we were producing the game, which meant we ran into a lot of difficulties code-wise. 
	The brief for this game project was visual narrative. We were told to create a world from any decade of the 20th century and to project that without the use of cut scenes and other exposition.
	We chose to portray the 1930's, and more specifically, the surrealism movement. </p>

	<center><img src="/images/game_art/surr/pipe.png" hspace="20" vspace="10" /></center>
	
	
<h4>Concept</h4>
	<p>Players take control of a 1930's gentleman who has been pulled into a surrealist world. 
	Upon entering this world, a mysterious villain steals your beautiful and manly moustache. 
	The player must then traverse dangerous and weird obstacles, solve puzzles and discover the 
	true meaning of this strange world, ultimately finding and defeating the villain to get his 
	moustache back and find his way home. 	</p>
	

<h4>Characters</h4>
<p><b>The Gentleman</b><br> The hero of our story and, most importantly, the owner of fantastic facial hair. 
He soon becomes the victim of a diabolical scheme by the mysterious Bag Face.
</p>
<p><b>Bag Face</b><br> The villain, a mysterious figure without a face or an identity. 
Inspired by the works of Rene Magritte.  
Fuelled by his desire to be someone, he steals the gentleman's beautiful moustache to have a distinguishing feature.    
</p>
<p><b>Elephant</b><br> A sad and lonely creature inspired by many Dali paintings such as <i>"Dream caused by the Flight of a Bee Around a Pomegranate a Second Before Awakening"</i>. 
The Gentleman will have to decide the fate of this creature to fulfil his goal. 
</p>

<center><img src="/images/game_art/surr/teeth.png" hspace="20" vspace="10" /></center>

<h4>Game Basics</h4>
<p>
The Gentleman has very few abilities to traverse the environment that he finds himself in. 
All the Players are able to do is move left and right, jump and interact with objects in the environment. 
The complexity comes in the strange and wonderful environments that the player explores. 
The environment will change and evolve around the player actions, opening paths for the player to explore and help reach his goal. 
</p>

<h4>The Environment</h4> <img src="/images/game_art/surr/sur_walk.gif" align="left" hspace="10" vspace="10" />
<p><b>The Look</b><br> The game world is inspired by many pieces of surrealist artwork from the 1930's by artist such as Rene Magritte, Salvador Dali and Max Ernst. 
The colours we have decided to use are earthy browns and reds, contrasted with light blues similar to that used in a lot of Dali landscapes. 
The world's geometry will be curvy and rounded to keep in line with the surrealist aesthetic and will inadvertently give the space a dream like feel. 
The Player will start in a space that is set in a 1930's apartment building that will be made to look authentic for the time. 
He will then be pulled into a surrealist dreamscape, where the majority of the adventure will take place.  
</p>
<p><b>Gravity</b><br> Although the world this game is set in is incredibly weird, gravitational pull will remain consistent throughout the Player's time in the game. 
The height and direction the player can jump will remain consistent throughout the game as well. 
The player will die if they fall from large distances, requiring the player to traverse environments carefully.
</p>
<p><b>The Background</b><br> There will be opportunities in the game where the player will have the ability to move into the background of the game. 
The player will also have the ability to come back into the foreground in unusual and interesting ways, which will change the Player's perception of the way that foreground and background interact in this world. 
</p>


<h4>Events</h4>
<p><b>A Cave</b><br> 
Once the Player falls into the cave he will face numerous challenges. 
First the Player will have to avoid dangers as he chases the elusive Bag Face. 
As the Bag Face runs, he will make the environment even more hazardous, forcing the Player to use lateral thinking to exit the cave.
<p><b>A Field</b><br> 
Within the field, the Player will have to use the perspective ability (see The Background) to successfully chase Bag Face. 
The Player's platforming skills will be put to test before he can ascend on the lemon to the Type Writer in the Sky.
</p>
<p><b>A Type Writer in the Sky</b><br> <img src="/images/game_art/surr/eye.png" align="right" hspace="10" vspace="10" />
Here the player will have to type 'Close' on the type writer to close the eye and proceed to the Elephant. 
The player will descend on the lemon back down to the field where he can now walk right to meet the Elephant.
</p>
<p><b>An Elephant's Legs</b><br> 
For the Player to successfully climb up the Elephant they must use what they have learned from 'A Field' and navigate though a maze of doors, testing the Player's memory as well as their platforming ability.
</p>
<p><b>An Elephant's Body</b><br> 
Once the Player has ascended the legs, he has to then progress past a series of platforming challenges that will lead the player inside the Elephant. 
From here the Player can move the Elephant across the screen until he reaches the peanut.
</p>
<p><b>A Cliff</b><br> 
Atop the cliff players will have a final confrontation with the infamous Bag Face. 
Once Bag Face is defeated the moustache will be returned to the Player and he will fall back into his bed.
</p>
	<center><img src="/images/game_art/surr/spoon.png" hspace="10" vspace="10" /><img src="/images/game_art/surr/spoon.png" hspace="10" vspace="10" /><img src="/images/game_art/surr/spoon.png" hspace="10" vspace="10" /></center>

</div>