<h2>Pandamine</h2>


<p class="center"><embed src="http://www.lapinsh.com/gamefiles/Pandamine.swf" 
volume="0"
width="1000" 
height="660" 

pluginspage="http://www.macromedia.com/go/getflashplayer"
></embed></p><br>

<center><h4>Escape your dark prison with the help of a magic light source</h4></center>

<h3>Concept and Design</h3>

<div class="info_2col">
	<p>
		<span class="field">Engine</span>
		<span class="value">Flash</span>
	</p>
	<p>
		<span class="field">Programming</span>
		<span class="value">AS2</span>
	</p>
	<p>
		<span class="field">Art</span>
		<span class="value">MS Paint</span>
	</p>
</div>

<div class="info_2col">
	<p>
		<span class="field">Artist & Designer</span>
		<span class="value">Anna Lapinsh</span>
	</p>
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">James Older</span>
	</p>
	
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">Michael Brown</span>
	</p>	
</div>


<div class="text_body">

<h4>About</h4>
	<p>
		<img src="/images/game_art/panda/panda_idle.gif" align="right" hspace="10" vspace="10" />

	Made for the <a href="http://www.creativefront.org/news-and-events/news/teams-for-brains-eden-2011-confirmed">Brains Eden</a> event; a 48 hour games jam in Cambridge.
	This was my first ever games jam and turned out to be a lot of fun. We got to really test our limits during that weekend and found out that if we really set out minds to it we could accomplish a lot.
	The whole experience was a huge success and we had a lot of fun. The brief of the weekend was just one word: "trapped".</p>

<h4>Concept</h4>
	<p>Players must escape the dark cave with the use of their magic wand. 
	Not only does it light their way, it can interact with the environment to activate platforms and help solve puzzles.
	Coins help the Player by leading the way, as well as giving him bonus points. 
	</p>

	<center><img src="/images/game_art/panda/process.png" hspace="20" vspace="10" /></center>	
	
<h4>Gameplay</h4>
<p><b>Movement</b><br>
	<img src="/images/game_art/panda/panda_walk.gif" align="left" hspace="10" vspace="10" />
	Players use the WASD keys to move the Panda Wizard. He moves at a steady pace and jumps on W.</p>
	
<p><b>Wand</b><br>
	The Wand is controlled by the mouse. It can be used as a light source. If the Player hovers his mouse over certain platforms, they will activate. 
	Originally, the Wand would also be upgradable to contain more powers - such as lighting torches and interacting with water.
	Due to time constraints however, this was pulled.</p>
	
<p><b>Platforms</b><br>
	There are three types of Platforms in the game. 
	<ul><li>Blue Platforms: Once activated these Platforms can be touched and stood on</li>
	<li>Red Platforms: Once activated, these Platforms cannot be touched or stood on and the character can simply step through them</li>
	<li>Orange Platforms: Once activated, these Platforms start to move at a regular pace</li>
	</ul>
	
	<center><img src="/images/game_art/panda/turns_off_platform1.gif" hspace="20" vspace="10" /></center>
	
	</p>
	
<p><b>Bonus Coins</b><br>
	Coins are placed around the environment for the Player to pick up. When the Player steps onto them he automatically picks them up and they get tallied in the upper left hand side of the screen.
	Coins are used to guide the Player around the environment and also create a sense of worthwhile gameplay. Originally, coins were intended to have a bigger impact, but due to time constraints, this feature had to be cut.
	
	<center><img src="/images/game_art/panda/coin_spin.gif" hspace="10" vspace="10" /><img src="/images/game_art/panda/coin_spin.gif" hspace="10" vspace="10" /><img src="/images/game_art/panda/coin_spin.gif" hspace="10" vspace="10" /></center>

	</p>

<p><b>Winning</b><br>
	The Player wins the game by completing a set of three levels and getting to the exit of the cave. </p>
</div>