<h2>Space Constructor</h2>

<div class="game_vid_preview">
<iframe width="600" height="300" src="http://www.youtube.com/embed/tpY75P95Dg0" frameborder="0" allowfullscreen></iframe>
</div>
<br>
<center><h4>Race to the heavens in this quick thinking construction game</h4></center>

<h3>Concept and Design</h3>


<div class="info_2col">
	<p>
		<span class="field">Engine</span>
		<span class="value">XNA</span>
	</p>
	<p>
		<span class="field">Programming</span>
		<span class="value">C#</span>
	</p>
	<p>
		<span class="field">Art</span>
		<span class="value">Photoshop</span>
	</p>
</div>

<div class="info_2col">
	<p>
		<span class="field">Artist & Designer</span>
		<span class="value">Anna Lapinsh</span>
	</p>
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">Michael Brown</span>
	</p>
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">James Older</span>
	</p>
</div>

<div class="text_body">

<h4>About</h4>		
	<p>
	<img src="/images/game_art/sc/sc_walk_cycle.gif" align="left" hspace="10" vspace="10" />
	Space Constructor was designed and created in 2011 as part of my degree. 
	The brief we were given allowed us 3 objects with 3 properties. 
	The game also had to have emergent gameplay. 
	We created a game that focused on building and reaching for the sky. 
	We wanted players to create huge structures and think up new ways to play this game.</p>
<h4>Concept</h4>
	<p>
		<img src="/images/game_art/sc/sc_death_anim.gif" align="right" hspace="10" vspace="10" />
	Players are tasked with climbing as high as they can in this puzzle action game. As the player starts
his ascent, his energy starts to constantly degrade. To keep himself energised the player must collect
Stars that litter the sky. However, collecting these starts may make the tower less sturdy and cause
some of the tower to collapse. Players will have to use quick thinking to build a tower that truly
stretches out to the heavens.</p>
<h4>Gameplay</h4>
	<p><b>Movement</b><br>
Players will be moving on a grid system. Movement will happen fluidly when the player has the left
or right button held down, however when the player lets go of the button the character will align
itself with the centre of the square.<br>

Players can jump two squares high and one square across. When descending the player will move
one square left or right with every square they move down.</p>

	<center><img src="/images/game_art/sc/sc_sprite_sheet.png" hspace="20" vspace="10" /></center>

<p><b>Building</b><br>
	<img src="/images/game_art/sc/block.png" align="right" hspace="10" vspace="10" />
To construct their tower players will need to place building blocks. This is achieved by players
jumping into the air and placing a block directly underneath themselves.<br>

Blocks will appear when the player presses the jump button whilst already in the air. Blocks will then
descend until there is a block for it to land onto or there is an adjacent block for it to attach itself to.</p>

<p><b>Falling</b><br>
Players will be able to create towers which are not completely stable. Any block that is placed three
blocks left or right of a block that is connected to the ground will fall down.</p>

<p><b>Energy</b><br>
Players' energy will constantly degrade and will eventually deplete ending the game. Players will be
able to top up their energy by collecting stars that will give extra energy to the player. These stars
will be scattered around the game environment for players to discover.</p>

<p><b>Scoring</b><br>
The score will equal the highest point that the player has been in the environment. Each square of
the grid will equal one meter.</p>

<p><b>Losing</b><br>
Players' energy will constantly degrade as they play the game. If this energy completely runs out the
player will receive a game over.</p>
	
	<center><img src="/images/game_art/sc/block.png" hspace="3" vspace="10" /><img src="/images/game_art/sc/block.png" hspace="3" vspace="10" /><img src="/images/game_art/sc/block.png" hspace="3" vspace="10" /> </center>

</div>
