<h2>Steam Express</h2>


<center><embed src="http://www.lapinsh.com/gamefiles/stex.swf" 
volume="0"
width="550" 
height="400" 

pluginspage="http://www.macromedia.com/go/getflashplayer"
></embed></center><br>

<center><h4>Deliver packages for a big bonus without causing a collision</h4></center>

<h3>Concept and Design</h3>

<div class="info_2col">
	<p>
		<span class="field">Engine</span>
		<span class="value">Flash</span>
	</p>
	<p>
		<span class="field">Programming</span>
		<span class="value">AS2</span>
	</p>
	<p>
		<span class="field">Art</span>
		<span class="value">MS Paint</span>
	</p>
</div>

<div class="info_2col">
	<p>
		<span class="field">Artist & Designer</span>
		<span class="value">Anna Lapinsh</span>
	</p>
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">Chris Lee</span>
	</p>
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">Sedar Balci</span>
	</p>
	<p>
		<span class="field">Programmer & Designer</span>
		<span class="value">Michael Brown</span>
	</p>		

</div>


<div class="text_body">

<h4>About</h4>
	<p>This is the second game that I made on the degree course. 
	The brief was to design a viral game. We made it intentionally score based so users would want to share it with their friends and compare scores.
	We also wanted to make it accessible to established IPs.
	I chose to do the art in MS Paint to achieve a pixel style feel to it which is friendly and yet niche at the same time.</p>

<center><img src="/images/game_art/train/train3.gif" hspace="0" vspace="10" /></center>	
	
<h4>Concept</h4>
	<p>Players are responsible for picking up packages and delivering them to the station. They can control the tracks by switching which way the junctions are pointing.
	The game gets harder as other trains enter the tracks and the Player must keep his eye on everything to avoid collisions.</p>
	
<h4>Gameplay</h4>
<p><b>Movement</b><br>
	The Player controls the track by right clicking on the switches at junctions. His primary concern is for his own Train, though he can steer the Enemy Trains in much the same way.</p>
	
<p><b>Enemy Trains</b><br>

	Enemy Trains travel on the same tracks as the Player Train. They can be controlled by the Player in the same way he controls his own Train. 
	They do not pick up Packages. 
If an Enemy Train hits another train, it will explode and dissapear from the game. As the game goes on, more and more Enemy Trains appear on screen, making it harder for the Player to steer away from collisions.</p>

<center><img src="/images/game_art/train/enemy.gif" hspace="0" vspace="10" /></center>

<p><b>Packages</b><br>
	Packages sit by the railtracks. If the Player's Train rides past them, he automatically picks them up. The Player can then steer his Train to the station, in which case the Package will be dropped off. 
	The more Packages the Player drops off at the station at once, the higher points bonus he will get. The Player can only hold a maximum of 5 Packages at once, at which point he will have to drop them off at the station.</p>
	
<p><b>Winning</b><br>
	The winning state is point based, so the game is potentially endless. The Player loses if his own Train collides with any other Train. If two Enemy Trains collide, they will simply dissapear and there is no penalty to the Player.</p>	
	
	</div>