
<h2>Animation</h2>

<div class="gallery">

	<div class="thumbs">
		<img src="/images/art/animation/thumbs/anim1.gif" />
		<img src="/images/art/animation/thumbs/anim2.gif" />
		<img src="/images/art/animation/thumbs/anim3.gif" />
		<img src="/images/art/animation/thumbs/anim4.gif" />
		<img src="/images/art/animation/thumbs/anim5.gif" />

	</div>


	<div class="viewer"></div>

	<p><b>Walk Cycle Pencil Test</b>
	<br>2008
	<br>Pencil test from an animation short course.
	</p>
	
	<p><b>Coin Pickup Test</b>
	<br>2008
	<br>Frame and timing test from an animation short course.
	</p>
	
	<p><b>Dog Walk Cycle Pencil Test</b>
	<br>2008
	<br>Pencil test from an animation short course.
	</p>
	
	<p><b>Pencil Test</b>
	<br>2010
	<br>Done for a small forum contest. Incidentally this won first place.
	</p>
	
	<p><b>Dog Walk Cycle Test</b>
	<br>2012
	<br>Decided to clean up my pencil tests. This is testing the fluidity.
	</p>

</div> 