<h2>Computer Graphics</h2>

<div class="gallery">

	<div class="thumbs">
		<img src="/images/art/cg/thumbs/ufo1.png" />
 		<img src="/images/art/cg/thumbs/ufo2.png" />
 		<img src="/images/art/cg/thumbs/ufo3.png" />
        
		<img src="/images/art/cg/thumbs/cg20.png" />
		<img src="/images/art/cg/thumbs/tree2.png" />
        <img src="/images/art/cg/thumbs/cg21.png" />
        
		<img src="/images/art/cg/thumbs/sur4.png" />
 		<img src="/images/art/cg/thumbs/sur5.png" />
		<img src="/images/art/cg/thumbs/sur7.png" />
        
 		<img src="/images/art/cg/thumbs/pi9.png" />        
 		<img src="/images/art/cg/thumbs/pi4.gif" />       
 		<div class="fake_img" style="background: url(/images/art/pixel/thumbs/pi14.png) top left no-repeat;" onclick="Site.toggleView(this, 'anim2');"></div>
       
		<img src="/images/art/cg/thumbs/td2.png" />       
		<img src="/images/art/cg/thumbs/td3.png" />    
		<div class="fake_img" style="background: url(/images/art/3d/thumbs/td5.png) top left no-repeat;" onclick="Site.toggleView(this, 'anim3');"></div>

  		<img src="/images/art/cg/thumbs/cg7.png" />
		<img src="/images/art/cg/thumbs/cg8.png" />	
		<img src="/images/art/cg/thumbs/cg9.png" />      

		<img src="/images/art/cg/thumbs/cg1.png" />
		<img src="/images/art/cg/thumbs/cg3.png" />
		<img src="/images/art/cg/thumbs/cg16.png" />	

	</div>


	<div class="viewer"></div>
        <p><b>UFO Screenshot</b>
	<br>Illustrator. Completed April 2013.
    <br>A concept screen for a simple mobile game. </p>   
        <p><b>Jeep and Missile details</b>
	<br>Illustrator. Completed April 2013.
    <br>A concept screen for a simple mobile game. </p>
        <p><b>UFO details</b>
	<br>Illustrator. Completed April 2013.
    <br>A concept screen for a simple mobile game. </p>

 
        <p><b>Tree Mock Up</b>
	<br>Pencil on paper, then photoshop. Completed March 2011.
    <br>For a social game we designed called Tree. </p>
        <p><b>Tree Icons</b>
	<br>Pencil on paper, then photoshop. Completed March 2011.
    <br>For a social game we designed called Tree. </p>
        <p><b>Tree Concept Animals</b>
	<br>Pencil on paper, then photoshop. Completed March 2011.
    <br>For a social game we designed called Tree. </p>

 
        <p><b>The Elephant</b>
	<br>Pencil on paper, then photoshop. 2010.
    <br>The Elephant is a massive character that Players can climb into. More about The Elephant <a href="/games/moustache">on the Moustache page.</a></p>
        <p><b>Outfit Concepts</b>
	<br>Pencil on paper, then photoshop. 2010.
    <br>The A few outfit and moustache samples for the main character. More <a href="/games/moustache">on the Moustache page.</a></p>
        <p><b>Character Sprite Sheet</b>
	<br>Pencil on paper, then photoshop. 2010.
    <br>The sprite sheet for the main character's walk and climb cycle. More <a href="/games/moustache">on the Moustache page.</a></p>
    
        <p><b>Pandamine</b>
	<br>2011
	<br>Main character in Pandamine. More about Pandamine <a href="http://www.lapinsh.com/games/pandamine">on the Pandamine page</a>.
	</p>    
        <p><b>Pirate Sprite Sheet</b>
	<br>2005
	<br>Close up of the sprite sheet made for a pirate gif. 
	</p>
        <p><b>Pet Sprites</b>
	<br>2011
	<br>Done in MS Paint, used Photoshop to animate the frames.
	<br>Pet sprites for users on a forum. Each done with a pet avatar refrence to work off of. 
	</p>

        <p><b>Plugman Wireframe</b>
	<br>2012
	<br>Plugman is a character that I designed. He can charge things up with his plug face.
	</p>
        <p><b>Plugman Render</b>
	<br>2012
	<br>Plugman is a character that I designed. He can charge things up with his plug face.
	</p>
        <p><b>Plugman Animation</b>
	<br>2012
	<br>Plugman is a character that I designed. He can charge things up with his plug face.
	</p>

    
		<p><b>Madame Boogey's Rabbits</b>
	<br>Pencil on paper, then photoshop, 2010
	<br>A three stage rabbit; baby, child and adult. 
	</p>
		<p><b>Madame Boogey's Owls</b>
	<br>Pencil on paper, then photoshop, 2010
	<br>A three stage owl, with female and male variatons of the later stages.
	</p>
		<p><b>Merdog</b>
	<br>Pencil on paper, then photoshop, 2010
	<br>Two stage merdog.
	</p>
    
        <p><b>The Amazing Monkey Man!</b>
	<br>Pencil on paper, then photoshop. Completed March 2009.
    <br>I was trying for a more posterised style, something fun and not overly detailed. </p>
        <p><b>Daniela</b>
	<br>Pencil on paper, then photoshop 2009
	<br>Made for user Kthrina based on a photo of her.</p>
        <p><b>Scorn</b>
	<br>Pencil on paper, then photoshop, 2009
	<br>Made for a user based on their avatar.
	</p>
	
  
	<div id="anim2" class="viewer_set" style="padding-top: 40px;">
		<img src="/images/art/pixel/bq1.gif" />
		<br>
		<img src="/images/art/pixel/bq4.gif" />
		<img src="/images/art/pixel/bq5.gif" />
		<img src="/images/art/pixel/bq6.gif" />
		<img src="/images/art/pixel/bq7.gif" />
		<img src="/images/art/pixel/bq8.gif" />
		<img src="/images/art/pixel/bq12.gif" />
		<br>
		<img src="/images/art/pixel/bq2.gif" />
		<img src="/images/art/pixel/bq3.gif" />
		<img src="/images/art/pixel/bq10.gif" />
		<img src="/images/art/pixel/bq15.gif" />
		<br>
		<img src="/images/art/pixel/bq13.gif" />
		<img src="/images/art/pixel/bq11.gif" />
		<img src="/images/art/pixel/bq9.gif" />	
		<img src="/images/art/pixel/bq14.gif" />
		
	</div>
    
	<div id="anim3" class="viewer_set" style="padding-top: 60px;">
	<iframe width="600" height="300" src="http://www.youtube.com/embed/Gc5NzMalnk4" frameborder="0" allowfullscreen></iframe>

	</div>
</div>