<h2>Art</h2>

<a href="/art/cg"><img src="/images/index_art/art/1.png" align="left" hspace="10" vspace="10" border="0"/></a> 
<h3><a href="/art/cg">Computer Graphics</a></h3>

<!--<a href="/art/pixel"><img src="/images/index_art/art/2.png" align="left" hspace="10" vspace="10" border="0"/></a> 
<h3><a href="/art/pixel">MS Paint</a></h3>-->

<a href="/art/sketches"><img src="/images/index_art/art/3.png" align="left" hspace="10" vspace="10" border="0"/></a> 
<h3><a href="/art/sketches">Traditional</a></h3>

<!--<a href="/art/3d"><img src="/images/index_art/art/4.png" align="left" hspace="10" vspace="10" border="0"/></a> 
<h3><a href="/art/3d">3DS Max</a></h3>-->

<a href="/art/animation"><img src="/images/index_art/art/5.png" align="left" hspace="10" vspace="10" border="0"/></a> 
<h3><a href="/art/animation">Animation</a></h3>