<h2>MS Paint</h2>

<div class="gallery">

	<div class="thumbs">

		<img src="/images/art/pixel/thumbs/pi9.png" />
		<img src="/images/art/pixel/thumbs/p10.png" />
		<img src="/images/art/pixel/thumbs/pi11.png" />		
		<div class="fake_img" style="background: url(/images/art/pixel/thumbs/pi14.png) top left no-repeat;" onclick="Site.toggleView(this, 'anim2');"></div>
		<img src="/images/art/pixel/thumbs/pi1.png" />
		<img src="/images/art/pixel/thumbs/pi3.png" />
		<div class="fake_img" style="background: url(/images/art/pixel/thumbs/pxthum.png) top left no-repeat;" onclick="Site.toggleView(this, 'anim1');"></div>
		<img src="/images/art/pixel/thumbs/pi4.gif" />
		<img src="/images/art/pixel/thumbs/pi5.png" />
		<img src="/images/art/pixel/thumbs/pi13.png" />
		<img src="/images/art/pixel/thumbs/pi6.png" />
		<img src="/images/art/pixel/thumbs/pi7.gif" />
		<img src="/images/art/pixel/thumbs/pi8.gif" />	
	</div>

	<div class="viewer"></div>

	<p><b>Pandamine</b>
	<br>2011
	<br>Main character in Pandamine. More about Pandamine <a href="http://www.lapinsh.com/games/pandamine">on the Pandamine page</a>.
	</p>
	
	<p><b>Hot Dog</b>
	<br>2010
	<br>Look how happy he is!
	</p>
	
	<p><b>Doodles</b>
	<br>2010
	<br>Simple little doodles that I do while watching tv.
	</p>
	
	<p><b>Pet Sprites</b>
	<br>2011
	<br>Done in MS Paint, used Photoshop to animate the frames.
	<br>Pet sprites for users on a forum. Each done with a pet avatar refrence to work off of. 
	</p>
	
	<p><b>Soda Cans</b>
	<br>2008
	<br>Done as a bored project when looking at a sode can on my desk.
	</p>
	
	<p><b>Sketches</b>
	<br>2009
	<br>Done in MS Paint to loosen up before starting to work on sprites, etc. 
	</p>
	
	<p><b>Sprites</b>
	<br>2005
	<br>Sprites that were done off of one of my bases. I go back and add to these from time to time.
	</p>
	
	<p><b>Pirate Sprite Sheet</b>
	<br>2005
	<br>Close up of the sprite sheet made for a pirate gif. 
	</p>
	
	<p><b>Sheepos</b>
	<br>2008
	<br>Templates done for a sheep/ram pet. Each template has a different theme for the User to pick from.
	</p>
	
	<p><b>Sheepos</b>
	<br>2008
	<br>Templates done for a sheep/ram pet. Each template has a different theme for the User to pick from.
	</p>
	
	<p><b>Sheepos</b>
	<br>2008
	<br>The finished Sheepos, with names, owners and genders. Each finished preview has it's own theme, as chosen from the templates.
	</p>
	
	<p><b>Pixel Kingdom</b>
	<br>2007
	<br>Done in MS paint, used Adobe ImageReady to animate the frames.
	<br>I made these for a game. I never got around to programming it however.
	</p>
	
	<p><b>Pixel Kingdom</b>
	<br>2007
	<br>Done in MS paint, used Adobe ImageReady to animate the frames.
	<br>I made these for a game. I never got around to programming it however.
	</p>
	
	
	<div id="anim1" class="viewer_set" style="padding-top: 80px;">
		<img src="/images/art/pixel/001.gif" />
		<img src="/images/art/pixel/002.gif" />
		<img src="/images/art/pixel/003.gif" />
		<img src="/images/art/pixel/004.gif" />
		<img src="/images/art/pixel/005.gif" />
		<br>
		<img src="/images/art/pixel/006.gif" />
		<img src="/images/art/pixel/007.gif" />
		<img src="/images/art/pixel/008.gif" />
		<img src="/images/art/pixel/015.gif" />
		<img src="/images/art/pixel/010.gif" />
		<br>
		<img src="/images/art/pixel/012.gif" />
		<img src="/images/art/pixel/013.gif" />
		<img src="/images/art/pixel/014.gif" />
		<img src="/images/art/pixel/016.gif" />
		<img src="/images/art/pixel/011.gif" />
		<br>
		<img src="/images/art/pixel/009.gif" />

	</div>

	<div id="anim2" class="viewer_set" style="padding-top: 40px;">
		<img src="/images/art/pixel/bq1.gif" />
		<br>
		<img src="/images/art/pixel/bq4.gif" />
		<img src="/images/art/pixel/bq5.gif" />
		<img src="/images/art/pixel/bq6.gif" />
		<img src="/images/art/pixel/bq7.gif" />
		<img src="/images/art/pixel/bq8.gif" />
		<img src="/images/art/pixel/bq12.gif" />
		<br>
		<img src="/images/art/pixel/bq2.gif" />
		<img src="/images/art/pixel/bq3.gif" />
		<img src="/images/art/pixel/bq10.gif" />
		<img src="/images/art/pixel/bq15.gif" />
		<br>
		<img src="/images/art/pixel/bq13.gif" />
		<img src="/images/art/pixel/bq11.gif" />
		<img src="/images/art/pixel/bq9.gif" />	
		<img src="/images/art/pixel/bq14.gif" />
		
	</div>
		




</div>