<h2>Traditional</h2>

<div class="gallery">

	<div class="thumbs">
		<img src="/images/art/sketches/thumbs/sk1.png" />
		<img src="/images/art/sketches/thumbs/sk18.png" />
		<img src="/images/art/sketches/thumbs/sk19.png" />
		<img src="/images/art/sketches/thumbs/sk2.png" />
		<img src="/images/art/sketches/thumbs/sk23.png" />
		<img src="/images/art/sketches/thumbs/sk17.png" />
		<img src="/images/art/sketches/thumbs/sk3.png" />
		<img src="/images/art/sketches/thumbs/sk15.png" />
		<img src="/images/art/sketches/thumbs/sk4.png" />
		<img src="/images/art/sketches/thumbs/sk21.png" />
		<img src="/images/art/sketches/thumbs/sk22.png" />		
		<img src="/images/art/sketches/thumbs/sk5.png" />
		<img src="/images/art/sketches/thumbs/sk6.png" />
		<img src="/images/art/sketches/thumbs/sk9.png" />
		<img src="/images/art/sketches/thumbs/sk10.png" />
		<img src="/images/art/sketches/thumbs/sk11.png" />
		<img src="/images/art/sketches/thumbs/sk14.png" />
		<img src="/images/art/sketches/thumbs/sk20.png" />
	</div>


	<div class="viewer"></div>

	<p><b>Tiger Study</b>
	<br>Pencil, 2008
	<br>From photograph refrence.
	</p>
	
	<p><b>Tiger Study</b>
	<br>Pencil, 2008
	<br>From photograph refrence.
	</p>
	
	<p><b>Tiger Study</b>
	<br>Colour pencils, 2008
	<br>From photograph refrence.
	</p>
	
	<p><b>Plant Study</b>
	<br>Pencil, 2008
	<br>From a plant that survived in my bedroom.
	</p>
	
	<p><b>Plant Study</b>
	<br>Pencil, 2008
	<br>Result of a trip to the zoo.
	</p>
	
	<p><b>Plant Study</b>
	<br>Colour pencils, pencils, 2008
	<br>From photograph refrence.
	</p>
	
	<p><b>Human Study</b>
	<br>Pencil, 2008
	<br>From photograph refrence.
	</p>
	
	<p><b>Hand Study</b>
	<br>Colour pencils, markers, 2008
	<br>All drawn with one hand occupied. 
	</p>
	
	<p><b>Media Study</b>
	<br>Marker, pencils, pencil, colour pencils, 2008
	<br>When in doubt, draw your surroundings.
	</p>
	
	<p><b>Robot Girls</b>
	<br>Colour pencils and markers, 2008
	<br>Did this to practice some different techniques with pencils and markers.
	</p>
	
	<p><b>Kinks</b>
	<br>Pencil, 2008
	<br>Based on characters from a user's avatar on a forum.
	</p>
	
	<p><b>Character</b>
	<br>Pencil, 2008
	<br>Character design based on my sister.
	</p>

	<p><b>Spear Boy</b>
	<br>Pencil, 2008
	<br>Based on a character from a user's avatar on a forum.
	</p>
	
	<p><b>Genie</b>
	<br>Pencil, 2008
	<br>Based on a character from a user's avatar on a forum.
	</p>
	
	<p><b>Clouds</b>
	<br>Pencil, 2008
	<br>Based on a character from a user's avatar on a forum.
	</p>
	
	<p><b>Scythe</b>
	<br>Pencil, 2008
	<br>Based on a character from a user's avatar on a forum.
	</p>
	
	<p><b>Balance</b>
	<br>Pencil, 2008
	<br>Based on a character from a user's avatar on a forum.
	</p>
	
	<p><b>Wings</b>
	<br>Pencil, 2008
	<br>Based on a character from a user's avatar on a forum.
	</p>

</div>