

<h2>3DS Max</h2>

<div class="gallery">

	<div class="thumbs">
		<img src="/images/art/3d/thumbs/td2.png" />
		<img src="/images/art/3d/thumbs/td3.png" />
		<img src="/images/art/3d/thumbs/td4.png" />
		<div class="fake_img" style="background: url(/images/art/3d/thumbs/td5.png) top left no-repeat;" onclick="Site.toggleView(this, 'anim3');"></div>
	</div>


	<div class="viewer"></div>

	<p><b>Plugman Wireframe</b>
	<br>2012
	<br>Plugman is a character that I designed. He can charge things up with his plug face.
	</p>

	<p><b>Plugman Render</b>
	<br>2012
	<br>Plugman is a character that I designed. He can charge things up with his plug face.
	</p>
	
	<p><b>Plugman Render</b>
	<br>2012
	<br>Plugman is a character that I designed. He can charge things up with his plug face.
	</p>
	
	<p><b>Plugman Animation</b>
	<br>2012
	<br>Plugman is a character that I designed. He can charge things up with his plug face.
	</p>

	<div id="anim3" class="viewer_set" style="padding-top: 60px;">
	<iframe width="600" height="300" src="http://www.youtube.com/embed/Gc5NzMalnk4" frameborder="0" allowfullscreen></iframe>

	</div>
	
</div> 