<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Anna Lapinsh - Game Designer Portfolio</title>
		<link rel="stylesheet" href="/css/style.css" />
        <link href='http://fonts.googleapis.com/css?family=Maven+Pro|Sacramento' rel='stylesheet' type='text/css'>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
		<script src="/js/site.js"></script>
	</head>

	<body>
		<div class="frame">
            <header>
    			<h1><span class="intro">Hello.<br />My name is</span> <span class="name">Anna Lapinsh</span></h1>
                <h2>I design games &amp; create art</h2>
            </header>

            <?php echo $this->Navigation(); ?>

			<article>
			<?php
			echo $this->layout()->content;
			?>

			</article>

            <footer>
                <span class="left">&copy; <?php echo date('Y'); ?> Anna Lapinsh</span>
                <a href="http://cloakedninjas.co.uk" class="ninja" target="_blank"></a>
            </footer>
		</div>
		<script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-40368903-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
	</body>
</html>