<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Anna Lapinsh - Game Designer Portfolio</title>
		<link rel="stylesheet" href="/css/style.css" />
        <link href='http://fonts.googleapis.com/css?family=Maven+Pro|Sacramento' rel='stylesheet' type='text/css'>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
		<script src="/js/site.js"></script>
	</head>

	<body>
		<div class="frame">
            <header>
    			<h1><span class="intro">Hello.<br />My name is</span> <span class="name">Anna Lapinsh</span></h1>
                <h2>I design games &amp; create art</h2>
            </header>

            <?php echo $this->Navigation(); ?>

			<article>
			<?php
			echo $this->layout()->content;
			?>

			</article>

            <footer>
                <span class="left">&copy; <?php echo date('Y'); ?> Anna Lapinsh</span>
                <a href="http://cloakedninjas.co.uk" class="ninja" target="_blank"></a>
            </footer>
		</div>
	</body>
</html>