


<img src="/images/about/me.png" align="left" hspace="10" vspace="10" /> 
<h2>About</h2>

<a href="http://uk.linkedin.com/pub/anna-lapinsh/54/39b/75b" target="_blank"><img src="/images/about/linkedin.png" border="0" hspace="2" vspace="2" /></a>
<a href="https://twitter.com/treslapin" target="_blank"><img src="/images/about/twitter.png" border="0" hspace="2" vspace="2" /></a>
<a href="http://www.facebook.com/anna.lapinsh" target="_blank"><img src="/images/about/facebook.png" border="0" hspace="2" vspace="2" /></a>

<br><br>
Hello. My name is Anna. 
<br><br>
I don't own a tablet - all digital work is done with a mouse.
<br><br>
I like cakes.