<h2>Web Version CV</h2>
<h4>About</h4>
<p>I have been employed as a designer at Hooplo Media since August 2011, running this work parallel
with my degree up until it's completion in June 2012. I am aiming to extend my professional
portfolio into the art and conceptual fields within the games industry. </p>

<h4>Experience</h4>

<dl><dt><b>August 2011 - Present: Game Designer at Hooplo Media</b>

<dd>Role: Game concept design, evaluation and balancing. 
Researching, creating and pitching new ideas, as well as expanding and redesigning existing games.
As lead designer, I was head of a division of programmers and artists from beginning of game concept until 
prototype production. </dl>

<br><b>Published Games:</b>
<ul><li><i><a href="http://www.facebook.com/UsainBoltAthletics">Usain Bolt Athletics</a></i> 
<li><i><a href="http://www.facebook.com/footygame">Cristiano Ronaldo Footy</a></i> 
</ul>
<br><b>Unpublished Games:</b>
<ul>
<li>Worked extensively on a social collectible card game for a major fantasy war-game IP, from concept to 
creation. 
<li>Worked extensively on a tie-in social game for a major fantasy RPG IP.
<li>Worked on multiple mini games for a standalone platform, from concept to creation.
<li>Lead designer on a tie-in mobile mini game for a major fantasy MMORPG IP. 
</ul>

<h4>Skills & Qualifications</h4>
<ul>
<li>Game concept design
<li>Game architecture design
<li>Strong concept and pitch presentation
<li>Paper prototyping and storyboarding 
<li>Strong concept art design
<li>Game systems, mechanics and UI
<li>Game tuning and balancing
<li>Level and map design 
<li>Story and narrative design
<li>Excellent documentation
<li>Excellent research and evaluation
<li>Strong written and verbal communication
<li>Familiar with various monetisation strategies
<li>Experience with social games
<li>Experience with mobile games
<li>Fluent English and Russian language skills
<li>Basic Finnish and French language skills 
</ul>

<h4>Tools</h4>
<ul>
<li>Proficient in Photoshop & Illustrator
<li>Proficient in 3DS Max
<li>Proficient in Microsoft Office (Word, PowerPoint , Excel, etc.) 
<li>Moderate programming skills in Flash (AS2), C# (XNA), Unity (JavaScript)
<li>ASET Degree in Web Design (HTML & CSS)
</ul>



<h4>Education</h4>

<dl><dt>2009 - 2012: London College of Communication
<dd>BA in Interactive Games Design
</dl>
<dl><dt>2005 - 2009: Kulosaaren Yhteiskoulu (Kulosaari Secondary School)
<dd>A-level English Language & Literature, Art & Design, Psychology
</dl>
1998 - 2005: International School of Helsinki<br><br>