<h3>CV</h3>
<h4>About</h4>
<p>I have been employed as a designer at Hooplo Media since August 2011, running this work parallel
with my degree up until it's completion in June 2012. I am aiming to extend my professional
portfolio into the art and conceptual fields within the games industry. </p>

<h4>Experience</h4>

<dl><dt><b>August 2011 - Present: Junior Games Designer at Hooplo Media</b>

<dd>Role: Game concept design, evaluation and balancing. Researching, creating and
pitching ideas, as well as expanding and redesigning existing games.</dl>

<br><b>Published Games:</b>
<ul><li><i><a href="http://www.facebook.com/UsainBoltAthletics">Usain Bolt Athletics</a></i> 
</ul>
<br><b>Unpublished Games:</b>
<ul>
<li>Worked extensively on a social collectible card game for a major fantasy
war-game IP, from concept to creation.
<li>Worked extensively on a tie-in social game for a major fantasy RPG IP.
<li>Worked on multiple mini games for a standalone platform, from concept to creation.
</ul>

<h4>Education</h4>

<dl><dt>2009 - 2012: London College of Communication</dt>
<dd>BA in Interactive Games Design</dd>
</dl>
<dl><dt>2005 - 2009: Kulosaaren Yhteiskoulu (Kulosaari Secondary School)
<dd>A-level English Language & Literature, Art & Design, Psychology
</dl>
1998 - 2005: International School of Helsinki<br><br>

<h4>Skills & Qualifications</h4>
<ul>
<li>Proficient in Photoshop & Illustrator

<li>Proficient in 3DS Max

<li>Moderate programming skills in Flash (AS2), C# (XNA), Unity (JavaScript)

<li>ASET Degree in Web Design (HTML & CSS)

<li>Fluent English language skills

<li>Fluent Russian language skills

<li>Moderate Finnish language skills

<li>Basic French language skills

<li>Proficient in Microsoft Office (Word, PowerPoint , Excel, etc.)
</ul>